### ISSUE TITLE
air01 Arduino例程中驱动ST7735不能用来驱动ST7789

### ISSUE THREAD

**Issue by 1215548** [Air-duino/Arduino-AirMCU#74]
### 描述一下这个bug / Describe the bug

[https://arduino.luatos.com/tutorial-extras/ST7735.html#%E8%BD%AF%E4%BB%B6%E9%83%A8%E5%88%86](url)
根据例程改的引脚，发现并不能驱动ST7789
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/14362835/40cbce4a-4828-4464-9e69-d7a8ce27eebd)
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/14362835/d8a38bab-2800-491e-89f4-2f8c619bcf95)
 
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/14362835/0cd99a80-8c8c-43fc-ba61-18a5ad89167e)
 
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/14362835/775072b8-b3f1-427c-8607-9d7f7fbd1cee)
 

### 复现步骤 / To Reproduce

照上面原理图可以复现

### 如果正常，应该是什么样 / Expected behavior

理论上它应该能正常显示。

### 截图 / Screenshots

屏幕只亮了背光，相应电路焊接都是良好的

### 日志 / Logs

--

### 系统 / System

win11

### PACK包版本 / Version

1.01

### 验证

- [X] 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] 已经提供了完整的报错信息、日志、截图，没有经过删减。

**Comment by chenxuuu** [comment]
提供的代码不全，无法复现，如果持续未补全代码，issue将关闭处理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月25日(周一) 晚上9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Air-duino/Arduino-AirMCU] air01 Arduino例程中驱动ST7735不能用来驱动ST7789 (Issue #74)




 
描述一下这个bug / Describe the bug
 
https://arduino.luatos.com/tutorial-extras/ST7735.html#%E8%BD%AF%E4%BB%B6%E9%83%A8%E5%88%86
 根据例程改的引脚，发现并不能驱动ST7789
 
 
 

 

 
复现步骤 / To Reproduce
 
照上面原理图可以复现
 
如果正常，应该是什么样 / Expected behavior
 
理论上它应该能正常显示。
 
截图 / Screenshots
 
屏幕只亮了背光，相应电路焊接都是良好的
 
日志 / Logs
 
--
 
系统 / System
 
win11
 
PACK包版本 / Version
 
1.01
 
验证
  
 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
 
 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a minimal reproducible example of the bug.
 
 已经提供了完整的报错信息、日志、截图，没有经过删减。
